### ISSUE TITLE
Can't set blank data for a type REG_MULTI_SZ registry key via puppet

### ISSUE THREAD

**Issue by pgrant87** [puppetlabs/puppetlabs-registry#265]
## Describe the Bug
In https://tickets.puppetlabs.com/browse/MODULES-5625 the `An array registry value can not contain empty values` error message was added to account for zero length strings in MULTI_SZ not being allowed:

As per Microsoft documentation:https://docs.microsoft.com/en-us/windows/desktop/sysinfo/registry-value-types

```
A REG_MULTI_SZ string ends with a string of length 0. Therefore, it is not possible to include a zero-length string in the sequence. An empty sequence would be defined as follows: \0.
```

This doesn't accurately reflect the registry though as you can add a key with this type and give it no data manually with no issues. My guess here is that there is a difference between a zero length string and the apparent blank data field that is actually passed to the key when doing it manually.

Puppet should have parity and be able to add blank data in this instance

## Expected Behavior
Be able to set a blank value for a REG_MULTI_SZ registry key

## Steps to Reproduce
Apply the following resource on a windows node and it results in the `An array registry value can not contain empty values` error:

```
registry_value { 'hklm:system\foo\bar':
    ensure => present,
    value => 'test',
    type   => 'array',
    data   => [''],
}
```

## Environment
Module Version: 4.0.1
Puppet Version: 6
OS Name/Version: windows server 2012 (personal testing windows server 2019)

**Comment by LukasAud** [comment]
https://tickets.puppetlabs.com/browse/MODULES-11322
