### ISSUE TITLE
Issue with value that could be treated as a path

### ISSUE THREAD

**Issue by DimmKirr** [puppetlabs/puppetlabs-registry#35]
I'm having issues when having such construction:

<pre>
registry::value { '%systemroot%\\system32\\inetsrv\\':          
            key=> 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Antimalware\Exclusions\Paths',
            type   => dword,
            data   => "0",              
        }
</pre>

I also tried

<pre>
registry::value { '%systemroot%\system32\inetsrv\\':            
            key=> 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Antimalware\Exclusions\Paths',
            type   => dword,
            data   => "0",              
        }
</pre>

Please share some Idea, if I'm doing something wrong, but it seems like a bug to me, as provider treats backslashes in the name of the key as a part of the path to that key.

Thanks in advance.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
